### ISSUE TITLE
Ability to run transformation in production

### ISSUE THREAD

**Issue by doug-numetric** [trongnd/babel-plugin-transform-class-bound-properties#2]
This is the best solution I have found so far to binding class methods to `this`.  It's a shame it is turned off for production without a way to configure that.  I realize that changes the meaning of the language, so it's a bit of a foot gun, but it is both a performant and concise solution.

**Comment by trongnd** [comment]
Supported in version `1.0.2`, please use `production` option as below to enable this plugin in production mode.
```json
{
  "plugins": ["transform-class-bound-properties", { "production": true }]
}
```

**Comment by doug-numetric** [comment]
🤦‍♂️ It was right there on the npm page.  Sorry for the noise.
